name: CI/CD Pipeline Workflow

on:
  - push

jobs: 
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow"
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Scan for Vulnerabilities
        run: |
          docker run --rm -it -v "$PWD:/pwd" trufflesecurity/trufflehog:latest github --org=trufflesecurity
      - name: Install dependencies
        run: npm ci
      - run: echo "Pipeline ran succesfully!"