name: CI/CD Pipeline Workflow

on:
  - push

jobs: 
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow"
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Scan for Vulnerabilities
        uses: trufflesecurity/trufflehog@v3.90.2
        with: 
          extra_args: --results=verified,unknown
      - name: Install dependencies
        run: npm ci
      - run: echo "Pipeline ran succesfully!"